services:
  - type: web
    name: doggiegrowl-api
    env: node
    plan: starter
    buildCommand: "pnpm --filter api build"
    startCommand: "pnpm --filter api start"
    envVars:
      - key: MONGO_URI
        fromDatabase: { name: doggiegrowl-mongo, property: connectionString }
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: WEB_APP_URL
        value: https://doggiegrowl-web.onrender.com

  - type: web
    name: doggiegrowl-web
    env: static
    plan: starter
    buildCommand: "pnpm --filter web build"
    staticPublishPath: ./apps/web/out
    routes:
      - type: rewrite
        source: /api/*
        destination: https://doggiegrowl-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: doggiegrowl-mongo
    plan: starter
